// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeAagE48rwVIpPBXYsNiVlxHv153S94iM',
    appId: '1:622050406852:web:4ea202781db1eb8150b491',
    messagingSenderId: '622050406852',
    projectId: 'wechat-232de',
    authDomain: 'wechat-232de.firebaseapp.com',
    storageBucket: 'wechat-232de.appspot.com',
    measurementId: 'G-HC0M3HT5XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZAXrtQ1koKrGAIwIXkEJq7LaAFrXhYkY',
    appId: '1:622050406852:android:e730e88c79cec01550b491',
    messagingSenderId: '622050406852',
    projectId: 'wechat-232de',
    storageBucket: 'wechat-232de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9V2Z36DCvyucHm2dwX5YHUbSUKuVIX2U',
    appId: '1:622050406852:ios:c144e27209f447ed50b491',
    messagingSenderId: '622050406852',
    projectId: 'wechat-232de',
    storageBucket: 'wechat-232de.appspot.com',
    androidClientId: '622050406852-195pcfsh6d1a918ga67r8l0ksvqfgqpi.apps.googleusercontent.com',
    iosClientId: '622050406852-n98b2f1an380cmb9aq8ab224hhcnq427.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9V2Z36DCvyucHm2dwX5YHUbSUKuVIX2U',
    appId: '1:622050406852:ios:c144e27209f447ed50b491',
    messagingSenderId: '622050406852',
    projectId: 'wechat-232de',
    storageBucket: 'wechat-232de.appspot.com',
    androidClientId: '622050406852-195pcfsh6d1a918ga67r8l0ksvqfgqpi.apps.googleusercontent.com',
    iosClientId: '622050406852-n98b2f1an380cmb9aq8ab224hhcnq427.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
